fixtures:
  forge_modules:
    sshkeys:
      repo: 'puppetlabs-sshkeys_core'
      ref: '2.3.0'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '8.1.0'
  symlinks:
    common: "#{source_dir}"
