---
env:
- PUPPET_VERSION=2.7.13
- PUPPET_VERSION=3.2.1
notifications:
email: false
rvm:
- 1.9.3
- 1.8.7
matrix:
  allow_failures:
  - env: PUPPET_VERSION=2.7.13
language: ruby
before_script: "gem install --no-ri --no-rdoc bundler"
script: 'SPEC_OPTS="--format documentation" bundle exec rake spec'
gemfile: Gemfile
